version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - networkDB
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/userdb?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - EXCEL_DIRECTORY=/mnt/d/data-qlsc
    depends_on:
      - mysql-db
      - redis
    networks:
      - networkDB
    volumes:
      - D:\data-qlsc\data\history:/mnt/d/data-qlsc
      - D:\data-qlsc\data\logs:/mnt/d/logs

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - networkDB
  
  mysql-db:
    image: mysql:8.0.26
    ports:
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=userdb
      - MYSQL_SERVICE_PORT=3306
    volumes:
      - D:\data-qlsc\database:/var/lib/mysql
    networks:
      - networkDB

volumes:
  mysql_data:
  qlsc-history:

networks:
  networkDB:
    name: network
    driver: bridge